spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sassine_perf_in?serverTimezone=UTC&cachePrepStmts=true&useServerPrepStmts=true&rewriteBatchedStatements=true
    username: develop
    password: password
  jpa:
    generate-ddl: true
#   show-sql: true
    properties:
      hibernate:
        generate_statistics: true #enable JDBC Session Metric 
        order_inserts: true
#       order_updates: true
        jdbc:
          dialect: org.hibernate.dialect.MySQL5Dialect
          batch_size: 1000
#       cache:
#         use_second_level_cache: true